# Generated by Django 4.2.27 on 2026-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Vinculación contractual',
                'verbose_name_plural': 'Vinculaciones contractuales',
                'db_table': 'colaborador_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorCore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'colaborador_core',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoCore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('vigencia', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato_core',
                'managed': False,
            },
        ),
    ]
